// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzdW-5jQgWBBNCV_uupyvuXgn7KGV7y1A',
    appId: '1:915074933400:web:3c791a789b5cdd576be6ed',
    messagingSenderId: '915074933400',
    projectId: 'electrochat-e46c0',
    authDomain: 'electrochat-e46c0.firebaseapp.com',
    storageBucket: 'electrochat-e46c0.appspot.com',
    measurementId: 'G-05P2T2H27E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIL_VaPerEppGi74iV95maLVMMFSYp1Zw',
    appId: '1:915074933400:android:6808eddea7e2e1f56be6ed',
    messagingSenderId: '915074933400',
    projectId: 'electrochat-e46c0',
    storageBucket: 'electrochat-e46c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsW8NfUQh1K5f1Ie_fbXHUYTIGcvuS9UI',
    appId: '1:915074933400:ios:7ebb241084a9cb996be6ed',
    messagingSenderId: '915074933400',
    projectId: 'electrochat-e46c0',
    storageBucket: 'electrochat-e46c0.appspot.com',
    iosBundleId: 'com.cgg.gov.sampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsW8NfUQh1K5f1Ie_fbXHUYTIGcvuS9UI',
    appId: '1:915074933400:ios:7ebb241084a9cb996be6ed',
    messagingSenderId: '915074933400',
    projectId: 'electrochat-e46c0',
    storageBucket: 'electrochat-e46c0.appspot.com',
    iosBundleId: 'com.cgg.gov.sampleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzdW-5jQgWBBNCV_uupyvuXgn7KGV7y1A',
    appId: '1:915074933400:web:db06c0f5f48717956be6ed',
    messagingSenderId: '915074933400',
    projectId: 'electrochat-e46c0',
    authDomain: 'electrochat-e46c0.firebaseapp.com',
    storageBucket: 'electrochat-e46c0.appspot.com',
    measurementId: 'G-BNKB0G9SX2',
  );

}